# Generated by Django 3.0.4 on 2020-03-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
